# Generated by Django 3.1.7 on 2021-08-06 07:15

from django.db import migrations, models
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('introduction', models.TextField(blank=True, max_length=400)),
                ('icon', models.ImageField(blank=True, upload_to=profiles.models.icon_path, verbose_name='アイコン')),
            ],
        ),
    ]
