# Generated by Django 3.1.7 on 2021-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210604_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='アイコン'),
        ),
    ]
