# Generated by Django 3.1.7 on 2021-05-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210524_1723'),
        ('profiles', '0003_auto_20210524_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
