# Generated by Django 3.1.7 on 2021-06-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('data_library', '0002_auto_20210612_1516'),
        ('profiles', '0003_auto_20210612_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_libraries',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_library.datalibrary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
