# Generated by Django 3.1.7 on 2021-05-30 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20210530_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, default=None, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
