# Generated by Django 3.1.7 on 2021-08-06 07:15

import ckeditor_uploader.fields
import data_library.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToDataLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='data_library', validators=[data_library.validators.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
