# Generated by Django 3.1.7 on 2021-06-11 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommenToDataLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('comment_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='data_library')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField(max_length=20000, null=True)),
                ('comment', models.ManyToManyField(to='data_library.CommenToDataLibrary')),
                ('good', models.ManyToManyField(default=None, related_name='good', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
