# Generated by Django 3.1.7 on 2021-08-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalibrary',
            name='good',
            field=models.ManyToManyField(default=None, related_name='good', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datalibrary',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttodatalibrary',
            name='comment_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttodatalibrary',
            name='comment_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='data_library.datalibrary'),
        ),
        migrations.AddField(
            model_name='commenttodatalibrary',
            name='response_to',
            field=models.ManyToManyField(related_name='data_library_response_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
