# Generated by Django 3.1.7 on 2021-06-11 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommenToDataLibrary',
            new_name='CommentToDataLibrary',
        ),
        migrations.RenameField(
            model_name='datalibrary',
            old_name='uploaded_date',
            new_name='created_at',
        ),
    ]
