# Generated by Django 3.1.7 on 2021-07-14 13:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_library', '0003_commenttodatalibrary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttodatalibrary',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
