# Generated by Django 3.1.7 on 2021-07-19 12:37

import ckeditor_uploader.fields
import data_library.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_library', '0004_auto_20210714_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalibrary',
            name='data_file',
            field=models.FileField(upload_to='data_library', validators=[data_library.validators.validate_file]),
        ),
        migrations.AlterField(
            model_name='datalibrary',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
