# Generated by Django 3.1.7 on 2021-06-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='response_to',
            field=models.ManyToManyField(default=None, related_name='response_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='good_from',
            field=models.ManyToManyField(default=None, related_name='good_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
