# Generated by Django 3.1.7 on 2021-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210604_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='article.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.TextField(max_length=20),
        ),
    ]
