# Generated by Django 3.1.7 on 2021-04-08 13:52

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210408_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(verbose_name=registration.models.User),
        ),
    ]
