# Generated by Django 3.1.7 on 2021-05-31 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20210524_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='good_count',
        ),
        migrations.AddField(
            model_name='article',
            name='good_from',
            field=models.ManyToManyField(default=None, related_name='good_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
