# Generated by Django 3.1.7 on 2021-05-31 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20210531_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント日時')),
                ('good', models.IntegerField(default=0, verbose_name='いいねの数')),
                ('response_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_from', to=settings.AUTH_USER_MODEL)),
                ('response_to', models.ManyToManyField(default=None, null=True, related_name='response_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
            },
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(default=None, to='article.Comment'),
        ),
    ]
