# Generated by Django 3.1.7 on 2021-05-31 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210531_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='article.article'),
        ),
    ]
