# Generated by Django 3.1.7 on 2021-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210408_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='いいねの数'),
        ),
    ]
