# Generated by Django 3.1.7 on 2021-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
    ]
