# Generated by Django 3.1.7 on 2021-06-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
                ('good_from', models.ManyToManyField(related_name='commet_good_from', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(related_name='question_tag', to='question.QuestionTag')),
            ],
        ),
        migrations.CreateModel(
            name='CommentToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_question', to='question.question')),
                ('response_to', models.ManyToManyField(related_name='comment_response_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
