# Generated by Django 3.1.7 on 2021-07-04 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='good_from',
            field=models.ManyToManyField(related_name='commet_good_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='question_tag', to='question.QuestionTag'),
        ),
        migrations.AddField(
            model_name='commenttoquestion',
            name='comment_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttoquestion',
            name='comment_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_question', to='question.question'),
        ),
        migrations.AddField(
            model_name='commenttoquestion',
            name='response_to',
            field=models.ManyToManyField(related_name='comment_response_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
