# Generated by Django 3.1.7 on 2021-07-14 12:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210714_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttoquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
