# Generated by Django 3.1.7 on 2021-07-18 11:50

from django.db import migrations
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', registration.models.UserManager()),
            ],
        ),
    ]
