# Generated by Django 3.1.7 on 2021-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210325_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='アイコン'),
        ),
    ]
