# Generated by Django 3.1.7 on 2021-05-15 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followee_friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='_user_followees_+', through='registration.Follow', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中のユーザー'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', through='registration.Follow', to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_by',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_to',
        ),
    ]
