# Generated by Django 3.1.7 on 2021-05-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210515_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
