# Generated by Django 3.1.7 on 2021-05-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210522_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
