# Generated by Django 3.1.7 on 2021-07-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='titile',
            new_name='title',
        ),
    ]
